[workspace]
members = [
  "uniffi_bindgen",
  "uniffi_build",
  "uniffi_macros",
  "uniffi",
  "examples/arithmetic",
  "examples/geometry",
  "examples/rondpoint",
  "examples/sprites",
  "examples/todolist",
  "regression_tests/i356-enum-without-int-helpers",
]
