[workspace]
members = [
  "cargo_uniffi",
  "uniffi_bindgen",
  "uniffi_build",
  "uniffi_macros",
  "uniffi",
  "examples/arithmetic",
  "examples/geometry",
  "examples/rondpoint",
  "examples/sprites",
  "examples/todolist"
]
